version: '3.7'

services:
  nginx:
    image: nginx
    restart: always
    ports:
    - "8000:80"
    volumes:
    - ./learnnginx:/usr/share/nginx/html
  blog:
    image: nginx
    restart: always
    ports:
    - "8001:80"
    volumes:
    - ./learnnginx/blog:/usr/share/nginx/html/
